credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Admin
      password: $2b$12$uD5h7w69nyJSK1WDRcS71OQUAxjRmOzAeMtGhVmfE2ICo3qspgCk2
cookie:
  name: image_analyzer_cookie
  key: supersecretkey
  expiry_days: 30
